TebLocalPlannerROS:

 odom_topic: odom
    
 # Trajectory
  
 teb_autosize: True
 dt_ref: 0.7
 dt_hysteresis: 0.1
 global_plan_overwrite_orientation: True
 max_global_plan_lookahead_dist: 7.0
 force_reinit_new_goal_dist: 1.0
 feasibility_check_no_poses: 5
 global_plan_viapoint_sep: -0.1
 exact_arc_length: True
 publish_feedback: False

    
 # Robot
         
 max_vel_x: 1.5
 max_vel_x_backwards: 0.15
 max_vel_y: 0.0
 max_vel_theta: 1.5
 acc_lim_x: 0.15
 acc_lim_y: 0.01
 acc_lim_theta: 1.5
 min_turning_radius: 0.0 # diff-drive robot (can turn on place!)
 wheelbase: 0.0
 cmd_angle_instead_rotvelis: false

 footprint_model:
   type: "line"
   line_start: [-0.15, 0.0] # for type "line"
   line_end: [0.60, 0.0] # for type "line"

 # GoalTolerance
    
 xy_goal_tolerance: 0.31  # 0.10
 yaw_goal_tolerance: 0.11  # 0.05
 free_goal_vel: False
    
 # Obstacles
    
 min_obstacle_dist: 0.35 # This value must also include our robot radius, since footprint_model is set to "point".
 inflation_dist: 0.4
 include_costmap_obstacles: True
 legacy_obstacle_association: False
 obstacle_association_force_inclusion_factor: 1.5
 #just check difference:
 costmap_obstacles_behind_robot_dist: 1.5
 obstacle_poses_affected: 28
 #costmap_converter_plugin: ""
 costmap_converter_spin_thread: True
 costmap_converter_rate: 5

 # Optimization
    
 no_inner_iterations: 4
 no_outer_iterations: 3
 optimization_activate: True
 optimization_verbose: False
 penalty_epsilon: 0.1
 weight_max_vel_x: 2.0
 weight_max_vel_theta: 1.0
 weight_acc_lim_x: 1.0
 weight_acc_lim_theta: 1.0
 weight_kinematics_nh: 800.0
 weight_kinematics_forward_drive: 35.0
 weight_kinematics_turning_radius: 0.0
 weight_optimaltime: 15.0
 weight_obstacle: 11.0
 #weight_dynamic_obstacle: 10 # not in use yet

 # Homotopy Class Planner

 enable_homotopy_class_planning: True
 enable_multithreading: True
 simple_exploration: False
 max_number_classes: 4
 selection_cost_hysteresis: 1.0
 selection_obst_cost_scale: 100.0
 selection_alternative_time_cost: False
 
 roadmap_graph_no_samples: 15
 roadmap_graph_area_width: 6
 h_signature_prescaler: 1.0
 h_signature_threshold: 0.1
 obstacle_keypoint_offset: 0.1
 obstacle_heading_threshold: 1.0
 visualize_hc_graph: False
